version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "09:00"
    target-branch: beta
    groups:
      github_action-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 0

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:00"
    target-branch: stable
    cooldown:
      default-days: 0
