name: Clean untagged Docker Packages

on:
  schedule:
    - cron: '10 3 * * *'
  workflow_dispatch:

jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
      - name: purge packages
        uses: dylanratcliffe/delete-untagged-containers@v1.2.3
        with:
          package_name: ${{ github.event.repository.name }} 
          token: ${{ github.token }}
